import ExcelJS from "exceljs";
import type { GroupedItem } from "./groupItems";
import { isExcludedHsCode, isNonItemCategory } from "./allowedHsCodes";

export async function generateCategorizedExcel(
  grouped: GroupedItem[],
  options?: { documentName?: string }
): Promise<Buffer> {
  const filtered = grouped.filter(
    (row) => !isExcludedHsCode(row.hsCode) && !isNonItemCategory(row.category)
  );
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Customs Categorization Portal";
  const sheet = workbook.addWorksheet(
    options?.documentName ?? "Categorized Packing List",
    {
      headerFooter: {
        firstHeader: options?.documentName ?? "Categorized Packing List",
        firstFooter: "Generated by HS Portal",
      },
    }
  );

  sheet.columns = [
    { header: "HS Code", key: "hsCode", width: 14 },
    { header: "Category", key: "category", width: 28 },
    { header: "Description", key: "finalDescription", width: 45 },
    { header: "Total Quantity", key: "totalQuantity", width: 16 },
    { header: "Unit", key: "unit", width: 10 },
  ];

  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FFE0E7F0" },
  };

  for (const row of filtered) {
    sheet.addRow({
      hsCode: row.hsCode,
      category: row.category,
      finalDescription: row.finalDescription,
      totalQuantity: row.totalQuantity,
      unit: row.unit ?? "PCS",
    });
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
